feat(pageHeader): rename property to withoutBackground following design review
carbon-design-system/ibm-cloud-cognitive pull request #1455
Opened 2021-11-18 14:58 UTC by lee-chase

Contributes to #1310

Deprecates the `hasBackgroundAlways` in favour of `withoutBackground` the default result remains the same.

#### What did you change?
Deprecated the `hasBackgroundAlways`
Added deprecated test for `hasBackgroundAlways`
Added `withoutBackground` prop and test

#### How did you test and verify your work?
Ran tests and storybook.

2021-11-22 21:33 UTC, dcwarwick requested changes

2021-11-22 21:33 UTC, dcwarwick commented on packages/cloud-cognitive/src/components/PageHeader/PageHeader.js
>     * for both the expend and collapse states of the button component used.
```suggestion
   * If `hasCollapseHeaderToggle` is set and `withoutBackground` is unset then assistive text is
   * required for both the expend and collapse states of the button component used.
```

2021-11-22 21:33 UTC, dcwarwick commented on packages/cloud-cognitive/src/components/PageHeader/PageHeader.js
>     * for both the expend and collapse states of the button component used.
```suggestion
   * If `hasCollapseHeaderToggle` is set and `withoutBackground` is unset then assistive text is
   * required for both the expend and collapse states of the button component used.
```

2021-11-22 21:33 UTC, dcwarwick commented on packages/cloud-cognitive/src/components/PageHeader/PageHeader.js
> +      // Determines if the withoutBackground should be one based on the header height or scroll
```suggestion
      // Determines the appropriate header background opacity based on the header config/height/scroll and the withoutBackground setting
```

2021-11-22 21:33 UTC, dcwarwick commented on packages/cloud-cognitive/src/components/PageHeader/PageHeader.js
> +      // only has toggle if requested and has withoutBackground
```suggestion
      // only has toggle if requested and does not have withoutBackground
```

2021-11-22 21:33 UTC, dcwarwick commented on packages/cloud-cognitive/src/components/PageHeader/PageHeader.js
> +   * When false some parts of the header gain a background if they stick to the top of the PageHeader on scroll.
```suggestion
   * Specifies if the PageHeader should appear without a background color, and defaults to the preferred `false` (a background color is shown).
   * Note that when `true` some parts of the header still gain a background if and when they stick to the top of the PageHeader on scroll.
```

2021-11-22 21:33 UTC, dcwarwick commented on packages/cloud-cognitive/src/components/PageHeader/PageHeader.test.js
> +    // When no withoutBackground is true this should result in the value 0 for opacity
```suggestion
    // When withoutBackground is true this should result in the value 0 for opacity
```

2021-11-22 21:33 UTC, dcwarwick commented on packages/cloud-cognitive/src/components/PageHeader/PageHeader.test.js
> +    // When no withoutBackground is false this should result in the value 0 for opacity
```suggestion
    // When withoutBackground is false this should result in the value 1 for opacity
```

2021-11-22 21:33 UTC, dcwarwick commented on packages/cloud-cognitive/src/components/PageHeader/PageHeader.test.js
> +    // When no hasBackgroundAlways is false this should result in the value 0 for opacity
```suggestion
    // When hasBackgroundAlways is false this should result in the value 0 for opacity
```

2021-11-24 11:11 UTC, lee-chase commented
Thanks, @dcwarwick added a `/falsy` to your `unset` suggestion to read `withoutBackground is unset/falsy`

2021-11-25 09:09 UTC, dcwarwick approved these changes
thanks - LGTM

2021-11-25 12:45 UTC, merged