feat(ProductiveCard): include ghost button in the Action Bar
carbon-design-system/ibm-cloud-cognitive pull request #2253
Opened 2022-09-02 10:41 UTC by punnoosewilson

Contributes to #2155

Allow Ghost buttons in the Action Bar

#### What did you change?
- Made changes inside the base components - Card and CardHeader
- Created Story - "**With Action Ghost Button**" 
- Included properties for:
-- name the button
-- onClick functionality
-- optional Icon

<img width="704" alt="image" src="https://user-images.githubusercontent.com/40118548/188122300-eb8678ad-7192-42c5-a840-8beb20533325.png">

#### How did you test and verify your work?
Test & Storybook

2022-09-02 15:28 UTC, davidmenendez requested changes
this is a good start, but i think we can utilize existing mechanisms to avoid adding unnecessary props. the component already uses `actionsPlacement` to position the action icons in the header or footer. since there can only be a single ghost button in a card i think that kind of approach would make sense too. so instead of adding a new action ghost button props i think what you could do is keep using the primary button props and instead add a prop like `ghostButtonPlacement` or something like that and then conditionally render the button in the header or footer.

one other thing that probably isn't clear at first- for the storybook prop descriptions you need to include new `Card` props in either or both `ProductiveCard.js` and `ExpressCard.js`

let me know if you have any questions and i'd be happy to work with you on this!

2022-09-05 10:22 UTC, punnoosewilson commented on packages/cloud-cognitive/src/components/Card/CardHeader.js
> +                className={`${blockClass}__actions-header-ghost-button ${
Used the `classnames` package to handle the conditional classes.

2022-09-05 12:37 UTC, punnoosewilson commented
> this is a good start, but i think we can utilize existing mechanisms to avoid adding unnecessary props. the component already uses `actionsPlacement` to position the action icons in the header or footer. since there can only be a single ghost button in a card i think that kind of approach would make sense too. so instead of adding a new action ghost button props i think what you could do is keep using the primary button props and instead add a prop like `ghostButtonPlacement` or something like that and then conditionally render the button in the header or footer.
> 
> one other thing that probably isn't clear at first- for the storybook prop descriptions you need to include new `Card` props in either or both `ProductiveCard.js` and `ExpressCard.js`
> 
> let me know if you have any questions and i'd be happy to work with you on this!

@davidmenendez 
I've updated the feature using primaryButton props and included "**primaryButtonPlacement**" prop for positioning the ghost button.

2022-09-09 14:50 UTC, qbi11y approved these changes

2022-09-12 15:40 UTC, merged