feat(combo-button): add `ComboButton` logic, story, and styles
carbon-design-system/ibm-cloud-cognitive pull request #233
Opened 2020-11-25 09:37 UTC by SimonFinney

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

#### Testing / Reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

2020-11-25 15:42 UTC, davidmenendez commented
in the story i'm unable to select any of the other options from the overflow menu.

2020-11-25 17:46 UTC, SimonFinney commented
Thanks @davidmenendez ! Apologies, I should've marked this a ready for design review 😅

2020-11-27 12:00 UTC, lee-chase requested changes
Looks good although changing the button in the dropdown did not work for me.

Also, will you be adding a ComboButton.mdx (in a later PR) to provide a component description/usecase?

2021-01-18 15:59 UTC, lee-chase approved these changes
LGTM

2021-01-20 02:24 UTC, cameroncalder approved these changes

2021-01-20 11:14 UTC, SimonFinney commented on packages/security/src/ComboButton/_combo-button.scss
> +@import '@carbon/import-once/scss/import-once';
I believe so, otherwise, we run the risk of CSS output being duplicated

2021-01-20 12:32 UTC, merged