docs: add external docs urls
carbon-design-system/ibm-cloud-cognitive pull request #2348
Opened 2022-10-11 17:37 UTC by mattrosno

Contributes to https://github.com/carbon-design-system/carbon-platform/issues/1380

Adds `externalDocsUrl`s to the index, so the IBM Products library's assets have `View asset docs` in Carbon Platform like this example below.

#### What did you change?

- add external docs urls
- clean up ibm security carbon yml formatting
- fix smart quote in description

#### Example

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1691245/195161288-49f1c11b-21e7-4b9a-a69b-b0b9f4f43af6.png">

2022-10-11 17:38 UTC, mattrosno commented
@jeanservaas @aubrey-oneal @aagonzales can you review? Not all indexed assets are documented in https://pages.github.ibm.com/cdai-design/pal, but for those I found, I added as `externalDocsUrl`s.

2022-10-20 21:29 UTC, elycheea requested changes
Just two URLs to fix for Create tearsheet narrow and page header.

2022-10-20 21:29 UTC, elycheea commented on packages/cloud-cognitive/carbon.yml
> +    externalDocsUrl: https://pages.github.ibm.com/cdai-design/pal/patterns/creation-flows/usage#wide-tearsheet
```suggestion
    externalDocsUrl: https://pages.github.ibm.com/cdai-design/pal/patterns/creation-flows/usage#narrow-tearsheet
```

2022-10-20 21:29 UTC, elycheea commented on packages/cloud-cognitive/carbon.yml
> +    externalDocsUrl: sign/pal/components/page-header/usage
```suggestion
    externalDocsUrl: https://pages.github.ibm.com/cdai-design/pal/components/page-header/usage
```

2022-10-20 21:53 UTC, mattrosno commented on packages/cloud-cognitive/carbon.yml
> +    externalDocsUrl: sign/pal/components/page-header/usage
Good catch - thanks!

2022-10-21 20:33 UTC, elycheea approved these changes

2022-10-26 13:45 UTC, merged