Button menu refactor
carbon-design-system/ibm-cloud-cognitive pull request #2442
Opened 2022-11-04 20:25 UTC by qbi11y

Contributes to #2076 

Refactored button menu, now uses button set instead of overflow menu. Verified variations with design spec.

#### What did you change?

#### How did you test and verify your work?

2022-11-08 20:19 UTC, matthewgallo commented on packages/cloud-cognitive/src/components/ButtonMenu/_button-menu.scss
> +  .#{$block-class}__sm .#{$carbon-prefix}--btn,
Can you remove these styles? Those must be left over from the nested menu prototype.

2022-11-08 20:20 UTC, matthewgallo commented on packages/cloud-cognitive/src/components/ButtonMenu/_button-menu.scss
> +    .#{$carbon-prefix}--accordion
Same comment as [here](https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/2442/files#r1017076898)

2022-11-18 21:31 UTC, elycheea requested changes

2022-11-18 21:32 UTC, elycheea commented
I mentioned this over Slack but we’ll also need to look into how we can get ButtonMenu and ComboButton working more consistently. Because ButtonMenu currently uses ButtonSet, navigating the menu is different than ComboButton although they look visually similar.

2022-11-18 21:55 UTC, qbi11y commented
I commented out some code causing issues because I didn't understand what was needed to resolve. I updated the PR so the team can see everything and offer insight. The test for ButtonWithOverFlow fails if I uncomment the section that mimics the user click. I know it mimics a click and is expecting a function to be called. All that seemed to be in place so not sure why it wasn't passing.

2022-11-23 00:01 UTC, qbi11y commented on packages/cloud-cognitive/src/components/ButtonMenu/ButtonMenu.js
> +  isDisabled: false,
I have started my storybook research :). I was working with the wrong assumption. Reading the documentation is helping me a bit. I can remove these as suggested.

2022-12-01 17:15 UTC, elycheea commented
After we fix and merge #2442, we can move ButtonMenu to canary + Storybook fixes.

2022-12-08 17:12 UTC, closed without merging