feat(Datagrid): adds FilterFlyout and FilterSummary v11
carbon-design-system/ibm-cloud-cognitive pull request #2525
Opened 2022-12-05 13:26 UTC by AlexanderMelox

Contributes to #2524 

Adds FilterFlyout and FilterSummary to v11

2022-12-08 20:10 UTC, davidmenendez approved these changes

2022-12-08 20:18 UTC, matthewgallo requested changes
One small request here, since the data model that is being used across stories has changed, can you update ClickableRow stories to include the fix I added [here](https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/2544/files). There is a date object that needs `.toString()`.

2022-12-12 17:26 UTC, AlexanderMelox commented
> One small request here, since the data model that is being used across stories has changed, can you update the `Clickable row with side panel` story to include the fix I added [here](https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/2544/files). There is a date object that needs `.toString()` called in order to render.

Added it to latest commit

2022-12-12 20:46 UTC, matthewgallo approved these changes

2022-12-14 15:41 UTC, merged