fix(DataGrid): date input to accept string date
carbon-design-system/ibm-cloud-cognitive pull request #2592
Opened 2023-01-05 12:11 UTC by Ratheeshrajan

Contributes to #2577 

The Datagrid inline edit component only works with Date objects and should be updated to accept strings as well.

#### What did you change?
`InlineEdit/InlineEditCell/InlineEditCell.js`
`utils/makeData.js`
`utils/getInlineEditColumns.js`
#### How did you test and verify your work?
Storybook

2023-01-06 03:46 UTC, elycheea requested changes
Based on how I interpreted the ticket, I think we also need to support typing in a date (as a string) in the DatePicker, which Carbon does already support.

![image](https://user-images.githubusercontent.com/1717398/210925463-945b7c7c-c6f5-45a9-bee0-e22a78d224a8.png)

But right now it looks like we set the DatePicker value so that it can’t be edited outside of the dropdown.

See Carbon [DatePicker docs](https://v7-react.carbondesignsystem.com/?path=/docs/components-datepicker).

![image](https://user-images.githubusercontent.com/1717398/210925937-dbc29941-3448-453c-9173-dbcf49890a0f.png)

2023-01-12 20:00 UTC, georgespano commented
Hello @elycheea. The issue is opened based on discussions @matthewgallo and I had with how we are using the DataGrid. The discussion was around the buildDate function returning null if the cell value was not an instance of date. Our dates are represented as strings and as such the function would return null and the cell would render empty, even though there was data for it. Looking at the changes made by @Ratheeshrajan I see that the issue would be resolved. Typing in dates is not something we are necessarily interested in, so you can handle adding that as a feature if you prefer.

One thing to mention to @Ratheeshrajan is that in the InlineEditCell.js DatePicker onChange function, it would be good to have it save the cell in the same format as the value. ie. if the incoming cell value was provided a string, then save the cell value as a string. Or even better, have a setting in the inlineEdit configuration for the date picker props that lets a user specify the format to set ie. "date", "string".

You can reach out to me in slack if you would like to discuss more.

Thanks!

2023-01-12 20:24 UTC, elycheea approved these changes
Approving after discussion with @georgespano although before we close #2577, I think we should try to simplify and support more default from Carbon date picker (if possible). We can discuss the current implementation once you’re back!

2023-01-12 20:25 UTC, elycheea approved these changes

2023-01-12 20:40 UTC, merged