fix(DataGrid): any option in filter panel flyout
carbon-design-system/ibm-cloud-cognitive pull request #2687
Opened 2023-02-21 15:51 UTC by Ratheeshrajan

Contributes to #2649 

Filter left panel & filter flyout: add "Any" options to Radio buttons and Dropdowns

#### What did you change?
`addons/Filtering/FilterFlyout.js`
`addons/Filtering/FilterPanel.js`

#### How did you test and verify your work?
Storybook

2023-02-21 16:39 UTC, AlexanderMelox commented
Waiting for #2669 to be merged to add v11 branch

2023-02-21 18:41 UTC, AlexanderMelox commented
@Ratheeshrajan One change from Design, can the 'Any' options for Radio and Dropdown be the default value?

2023-02-21 18:43 UTC, AlexanderMelox commented
<img width="1173" alt="Screenshot 2023-02-21 at 1 42 05 PM" src="https://user-images.githubusercontent.com/12755042/220431576-8c877871-abe7-45ab-85ee-a223df42d872.png">
<img width="1240" alt="Screenshot 2023-02-21 at 1 42 25 PM" src="https://user-images.githubusercontent.com/12755042/220431652-4b747e53-8293-4266-8de9-5896fa900c58.png">
 So should look like this for both Flyout and Panel

2023-02-22 09:48 UTC, Ratheeshrajan commented
@AlexanderMelox fixed the above comment.

2023-02-23 18:36 UTC, AlexanderMelox commented
@Ratheeshrajan I see your implementation works but it seems to have broken the logic for the shouldDisabledButtons state. Looking into it now

2023-02-23 18:37 UTC, AlexanderMelox commented on packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/Filtering/FilterFlyout.js
> +            {<RadioButton id="any" labelText="Any" value="Any" />}
no need for the curly braces
```suggestion
            <RadioButton id="any" labelText="Any" value="Any" />
```

2023-02-23 18:52 UTC, AlexanderMelox commented
Found a better solution, this doesn't interfere with the `shouldDisableButtons`state. 
1. Remove this line of code
```js
   if (
      filtersState[column].value === '' &&
      (type === DROPDOWN || type === RADIO)
    ) {
      filtersState[column].value = 'Any';
    }
```
2. For dropdown pass in this for `selectedItem`
```
selectedItem={
              filtersState[column].value === ''
                ? 'Any'
                : filtersState[column].value
            }
```
3. For `RadioButtonGroup` pass this in for `valueSelected`
```
valueSelected={
                filtersState[column].value === ''
                  ? 'Any'
                  : filtersState[column].value
              }
```

2023-02-23 21:39 UTC, AlexanderMelox requested changes

2023-02-23 21:39 UTC, AlexanderMelox commented on packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/Filtering/FilterFlyout.js
>            selectedItem={filtersState[column].value}
Also in the top on line 278 / 297
<img width="652" alt="Screenshot 2023-02-23 at 4 39 19 PM" src="https://user-images.githubusercontent.com/12755042/221036360-a7a0272d-752c-4179-81e9-73d4fa88527f.png">

2023-02-24 08:58 UTC, Ratheeshrajan commented
@AlexanderMelox Fixed the review comments and [V11 PR](https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/2701) added.

2023-02-24 17:42 UTC, AlexanderMelox commented on packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/Filtering/FilterFlyout.js
> +              : filtersState[column].value === ''
Sorry this should be like this
```suggestion
              : filtersState[column].value
```

2023-02-24 17:42 UTC, AlexanderMelox commented on packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/Filtering/FilterPanel.js
> +                : filtersState[column].value === ''
```suggestion
                : filtersState[column].value
```

2023-02-24 17:45 UTC, AlexanderMelox commented
@Ratheeshrajan Noticed there was an error, I suggested some changes up top

2023-02-27 15:45 UTC, AlexanderMelox approved these changes
Thank you for the changes @Ratheeshrajan! Looks good to me 🚀

2023-02-27 15:55 UTC, merged