fix(sidepanel toolbar): tooltip truncate issue fix
carbon-design-system/ibm-cloud-cognitive pull request #2786
Opened 2023-03-30 06:52 UTC by jagathgj

Contributes to #2485 

Sidepanel toolbar's icon tooltip truncate issue fixed 

#### What did you change?
position property changed from sticky to fixed 

#### How did you test and verify your work?
storybook

2023-03-30 19:16 UTC, matthewgallo commented
Changing from `sticky` to `fixed` seems to cause some layout issues, notably after the panel has scrolled.

![image](https://user-images.githubusercontent.com/10215203/228940827-5352dcf9-e902-4879-9db7-91e478b69446.png)

2023-03-30 20:30 UTC, elycheea requested changes
Looks like this addresses the tooltip overflow issue. Also may need some adjustment to the `top` and width with the switch to `position: fixed`. 👀 

<img width="535" alt="image" src="https://user-images.githubusercontent.com/1717398/228955963-34c55790-d90a-46b4-962b-2d3fc85f3995.png">

2023-04-04 07:15 UTC, jagathgj commented
I am pushing another change with tooltip alignment on 'start' because it would be better choice while in small screens. Here s the screenshot

<img width="737" alt="image" src="https://user-images.githubusercontent.com/29351394/229716443-80d3842e-98bd-4fa4-851a-17f7cfe85f90.png">

2023-04-12 03:43 UTC, elycheea approved these changes

2023-04-13 14:47 UTC, merged