chore: copy v1 animation for inline edit
carbon-design-system/ibm-cloud-cognitive pull request #2858
Opened 2023-04-12 17:31 UTC by lee-chase

Contributes to #1649 

- Corrects the icon size used in V11 inline-edit (v1 and v2)
- Corrects the animation to match v10 version

NOTE: There may be other issues but this PR is only to match the icon size and animation behaviour of V1.

#### What did you change?

Updated inline edit v1 and 2 CSS and js

#### How did you test and verify your work?

Storybook updated CSS snapshot

2023-04-12 19:58 UTC, davidmenendez requested changes
i'm seeing a weird bug here when invalid is true and then the input is focused. it probably has to do with the fact that the warning svg is outside the motion

2023-04-13 09:31 UTC, lee-chase commented
@davidmenendez yeah, that bug happens in both V10 and V11. Just wanted to get V10 and V11 in the same state before making additional PRs.

Also not sure if recent changes trashed the tooltip.

2023-04-13 11:50 UTC, lee-chase commented
Looks like the styling of the icon only button changed somewhat in V11. I've removed some of the CSS which was managing focus, hover etc as Carbon now appears to be styled in a way that is compatible with our input.

2023-04-14 15:48 UTC, davidmenendez approved these changes

2023-04-14 16:21 UTC, merged