fix: prefix not using global settings
carbon-design-system/ibm-cloud-cognitive pull request #331
Opened 2021-02-10 15:39 UTC by lee-chase

Carbon prefix should be retrieved from the global settings not directly from Carbon.

#### Changelog

m packages/experimental/src/components/PageHeader/ButtonSetWithOverflow.js 
m packages/experimental/src/components/PageHeader/TempComboButton.js

2021-02-10 20:20 UTC, davidmenendez requested changes
just one comment

2021-02-10 20:20 UTC, davidmenendez commented on packages/experimental/src/components/PageHeader/TempComboButton.js
> +          className={`${blockClass}--trigger  ${carbonPrefix}--btn ${carbonPrefix}--btn--primary ${carbonPrefix}--btn--field`}>
can you use the `cx` function for this please?

2021-02-11 11:53 UTC, SimonFinney reviewed
LGTM pending resolution of https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/331/files#r574049066

Additionally, what's the position on using the 'ready to merge' label? If there are multiple reviews on a PR, this will still trigger if one has approved and the other is still pending.

2021-02-12 11:31 UTC, lee-chase commented
> LGTM pending resolution of https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/331/files#r574049066
> 
> Additionally, what's the position on using the 'ready to merge' label? If there are multiple reviews on a PR, this will still trigger if one has approved and the other is still pending.

I've tended to add 'ready to merge' when I am happy, but it probably should not merge if there are outstanding change requests or multiple reviews required.

2021-02-23 19:52 UTC, davidmenendez approved these changes

2021-02-23 19:58 UTC, merged