docs(issue-template): draft 'definition of done', update 'CONTRIBUTING'
carbon-design-system/ibm-cloud-cognitive pull request #348
Opened 2021-02-17 11:16 UTC by SimonFinney

Contributes to #272 

#### Changelog

**New**

Add 'definition of done' to component or pattern issue template

**Changed**

Add additional clarity to component or pattern issue template and `CONTRIBUTING.md`

2021-02-17 17:26 UTC, matthewgallo commented on .github/ISSUE_TEMPLATE/component-or-pattern.md
> +- [ ] Accessibility tests for each use case
Might be helpful if we could provide an example of how to run this accessibility test. Or if this test is to be written for each component, an example of one in use.

2021-02-24 09:26 UTC, lee-chase approved these changes

2021-02-24 09:26 UTC, lee-chase commented on .github/ISSUE_TEMPLATE/component-or-pattern.md
> +- [ ] Custom class names can be supplied for additional style customization
What are props not used to customize as per Carbon?

2021-02-24 09:26 UTC, lee-chase commented on .github/ISSUE_TEMPLATE/component-or-pattern.md
> +- [ ] Additional props are
All props that have a functional/visual impact should be passed explicitly. What type of additional prop are we referring too?

2021-02-24 09:27 UTC, lee-chase requested changes
See comments

2021-02-26 17:39 UTC, closed without merging