Fix resizing of AboutModal
carbon-design-system/ibm-cloud-cognitive pull request #422
Opened 2021-03-09 15:18 UTC by moores2

Contributes to #390

Fix the problem with dynamic resizing of the AboutModal not enabling scrolling. Done by removing the ReactResizeDetector component and associated logic.

2021-03-09 17:07 UTC, moores2 commented on packages/experimental/src/components/AboutModal/AboutModal.js
> +                <React.Fragment key={i}>
Fixed

2021-03-09 17:07 UTC, moores2 commented on packages/experimental/src/components/AboutModal/AboutModal.js
> +          {legalText ? (
Fixed

2021-03-09 17:07 UTC, moores2 commented on packages/experimental/src/components/AboutModal/AboutModal.js
> +          {copyrightText ? (
Fixed

2021-03-09 17:22 UTC, davidmenendez approved these changes
looks good 👍

2021-03-09 17:24 UTC, dcwarwick requested changes
I love it when a defect can be addressed by simplifying and removing code! There's just one glitch I've spotted, when the height becomes extremely small the scroll-fade rises up over the modal header:

![image](https://user-images.githubusercontent.com/6385315/110511566-3f79e880-80fc-11eb-8a59-d1a7ebe0d42f.png)

2021-03-10 11:59 UTC, dcwarwick approved these changes

2021-03-10 11:59 UTC, merged