feat: card refactor
carbon-design-system/ibm-cloud-cognitive pull request #526
Opened 2021-03-25 21:15 UTC by davidmenendez

Contributes to #525 

This PR addresses refactoring the Card component to use this base & themed component pattern. Now the card component has been broken up into three separate ones. `Card`, `ExpressiveCard`, and `ProductiveCard` where the themed components are just wrappers for card.

```
import { Card }
...
export const ExpressiveCard = ({ props specific to the expressive card }) => <Card {...props} />
```

So the main idea here is to split up the components and their dependencies based on their specific use case. I removed the card from storybook because I think if we went this route we would encourage users to use the themed component and not the base, which is also why I removed the prop comments from card. There is some duplication of props and prop comments between the two themed components, but since we're relying on storybook for documentation I think it's just something we have to live with even though code duplication isn't ideal, but now when you look at the storybook for each component they now display the props that they actually depend on. previously when everything was in a single place we had received some feedback that looked like

> why is X a control in expressive when X is only applicable to productive

Now that's no longer a problem.

Using this pattern now all the shared code is found in the `Card` folder and anything specifically related to the themed components is found in their respective folder, which is mainly css. There is also some general cleanup going on here.

2021-03-27 13:08 UTC, lee-chase commented
@dcwarwick looks like you did not complete the review on this PR.

Sorry @davidmenendez I think we said we'd submitted a review.

2021-03-28 14:13 UTC, dcwarwick requested changes

2021-03-28 14:13 UTC, dcwarwick commented on packages/cloud-cognitive/src/components/Card/_card.scss
> +// Copyright IBM Corp. 2020, 2020
```suggestion
// Copyright IBM Corp. 2020, 2021
```

2021-03-28 14:13 UTC, dcwarwick commented on packages/cloud-cognitive/src/components/Card/_storybook-styles.scss
> +// Copyright IBM Corp. 2020, 2020
```suggestion
// Copyright IBM Corp. 2020, 2021
```

2021-03-28 14:13 UTC, dcwarwick commented on packages/cloud-cognitive/src/components/ExpressiveCard/ExpressiveCard.js
> +import React from 'react';
```suggestion
/**
 * Copyright IBM Corp. 2020, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
```

2021-03-28 14:13 UTC, dcwarwick commented on packages/cloud-cognitive/src/components/ExpressiveCard/ExpressiveCard.test.js
> + * Copyright IBM Corp. 2020, 2020
```suggestion
 * Copyright IBM Corp. 2020, 2021
```

2021-03-28 14:13 UTC, dcwarwick commented on packages/cloud-cognitive/src/components/ExpressiveCard/_expressive-card.scss
> +// Copyright IBM Corp. 2020, 2020
```suggestion
// Copyright IBM Corp. 2020, 2021
```

2021-03-28 14:13 UTC, dcwarwick commented on packages/cloud-cognitive/src/components/ExpressiveCard/_index.scss
> +// Copyright IBM Corp. 2020, 2020
```suggestion
// Copyright IBM Corp. 2020, 2021
```

2021-03-28 14:13 UTC, dcwarwick commented on packages/cloud-cognitive/src/components/ExpressiveCard/_storybook-styles.scss
> +// Copyright IBM Corp. 2020, 2020
```suggestion
// Copyright IBM Corp. 2020, 2021
```

2021-03-28 14:13 UTC, dcwarwick commented on packages/cloud-cognitive/src/components/ExpressiveCard/index.js
> +// Copyright IBM Corp. 2020, 2020
```suggestion
// Copyright IBM Corp. 2020, 2021
```

2021-03-28 14:13 UTC, dcwarwick commented on packages/cloud-cognitive/src/components/ProductiveCard/ProductiveCard.js
> +//
```suggestion
/**
 * Copyright IBM Corp. 2020, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
```

2021-03-28 14:13 UTC, dcwarwick commented on packages/cloud-cognitive/src/components/ProductiveCard/ProductiveCard.stories.js
> +// Copyright IBM Corp. 2020, 2020
```suggestion
// Copyright IBM Corp. 2020, 2021
```

2021-03-28 14:13 UTC, dcwarwick commented on packages/cloud-cognitive/src/components/ProductiveCard/ProductiveCard.test.js
> + * Copyright IBM Corp. 2020, 2020
```suggestion
 * Copyright IBM Corp. 2020, 2021
```

2021-03-28 14:13 UTC, dcwarwick commented on packages/cloud-cognitive/src/components/ProductiveCard/_index.scss
> +// Copyright IBM Corp. 2020, 2020
```suggestion
// Copyright IBM Corp. 2020, 2021
```

2021-03-28 14:13 UTC, dcwarwick commented on packages/cloud-cognitive/src/components/ProductiveCard/_productive-card.scss
> +@import '../../global/styles/carbon-settings';
```suggestion
//
// Copyright IBM Corp. 2020, 2021
//
// This source code is licensed under the Apache-2.0 license found in the
// LICENSE file in the root directory of this source tree.
//

@import '../../global/styles/carbon-settings';
```

2021-03-28 14:13 UTC, dcwarwick commented on packages/cloud-cognitive/src/components/ProductiveCard/_storybook-styles.scss
> +// Copyright IBM Corp. 2020, 2020
```suggestion
// Copyright IBM Corp. 2020, 2021
```

2021-03-28 14:13 UTC, dcwarwick commented on packages/cloud-cognitive/src/components/ProductiveCard/index.js
> +// Copyright IBM Corp. 2020, 2020
```suggestion
// Copyright IBM Corp. 2020, 2021
```

2021-03-29 17:31 UTC, davidmenendez commented
@dcwarwick 

> We don't need to explicitly destructure and rebuild props, because we can just collect the entire set of props and pass them through. 

I was thinking about this one a lot. my thinking is that this is another step to ensure the consumer is unable to pass an undesirable prop (accidentally or otherwise). since they're just wrappers for the card component it would still be possible to send productive only props to expressive and vice versa if we simply pass it as `...props`. it does mean more lines on our end, but i think going about it this way helps ensure less bugs and unwanted behavior for users.

2021-03-29 20:36 UTC, dcwarwick commented
@davidmenendez It's a good thought. The thing is, one of our guidelines calls for us to pass all 'extra' props through as HTML attributes onto the main HTML element, which the Carbon components also do. That means we need to include a spread `...rest` at the end of the props destructuring, and then add `...rest` when passing them through to the wrapped component. In fact, that was the review comment I originally started to make -- then we realised that if we're doing that then we might as well drop all the explicit destructuring, since any props passed in that we don't explicitly destructure will get passed across anyway.

2021-03-29 21:04 UTC, davidmenendez commented
that's a good point. i hadn't considered that. what do you think about creating a utility that strips undesired props? something like

```
/**
 * props should be an object of properties
 * blacklist should be an array of undesired property names
 */
const stripProps = (props, blacklist) => // object not containing blacklisted props
```

i think doing something like this will help cut down on bugs and consumer bug reports because ultimately with this kind of pattern there is a certain level of prop sharing between the base component and the wrapper components

2021-03-29 21:42 UTC, davidmenendez commented
@dcwarwick while I was able to add this new utility function to solve the prop problem I don't think we can remove the proptypes since ultimately these changes are here to benefit storybook and our documentation. so we will still have some redundancy there, but better safe than sorry, right? 😂

2021-03-30 09:52 UTC, dcwarwick approved these changes

2021-03-30 13:14 UTC, lee-chase commented on packages/cloud-cognitive/src/global/js/utils/props-helper.js
> +export const stripUnwantedProps = (props, blacklist) => {
@dcwarwick @davidmenendez  FYI 526 introduces a second pattern for stripping props, we should probably pick one and go with it.
This is from actionBarItem
const reservedProps = [
  'hasIconOnly',
  'kind',
  'size',
  'tooltipPosition',
  'tooltipAlignment',
  'type',
];
// Base props on Carbon Button
const propTypes = { ...Button.propTypes };
const defaultProps = { ...Button.defaultProps };
// Remove reserved props
reservedProps.forEach((prop) => {
  delete propTypes[prop];
  delete defaultProps[prop];
});

2021-03-31 10:04 UTC, dcwarwick requested changes

2021-03-31 14:49 UTC, davidmenendez commented on packages/cloud-cognitive/src/components/ExpressiveCard/ExpressiveCard.test.js
> +import '../../enable-all'; // must come before component is imported (directly or indirectly)
done

2021-03-31 18:32 UTC, dcwarwick submitted a review, later dismissed

2021-03-31 22:01 UTC, davidmenendez commented
@lee-chase @dcwarwick i've made a small additional update to move each card to a shared `Cards` folder in storybook to improve organization. 

<img width="227" alt="Screen Shot 2021-03-31 at 4 55 18 PM" src="https://user-images.githubusercontent.com/6370760/113216917-a9d90100-9242-11eb-83dc-62147360f7e1.png">

These storybook changes have been approved by design and they are very happy with the improved UX.

2021-03-31 22:10 UTC, dcwarwick approved these changes

2021-04-01 11:58 UTC, merged