Fix background of pagination inside wide tearsheet
carbon-design-system/ibm-cloud-cognitive pull request #747
Opened 2021-05-17 22:04 UTC by nertzy

This is directly related to #339.

#### What did you change?

We added two missing classes to the list of selectors that need to be "un-overridden" to get back to the correct look inside the wide tearsheet main area. 

#### How did you test and verify your work?

Copied the list of selectors from https://github.com/carbon-design-system/carbon/blob/ce0662896cb8919f1f11b70a1f4351750b6d7e07/packages/components/src/components/modal/_modal.scss#L49-L50 to add the missing classes.

2021-05-17 23:44 UTC, dcwarwick requested changes

2021-05-17 23:44 UTC, dcwarwick commented on packages/cloud-cognitive/src/components/Tearsheet/_tearsheet.scss
> +    .#{$prefix}--pagination__control-buttons--light,
I think these two classes are not in fact used, because, rather inconsistently, Pagination does not have a 'light' prop.

```suggestion
```

2021-05-17 23:49 UTC, dcwarwick commented
Thank you @nertzy for the PR. I copied this exact list of cases from Carbon, so I guess pagination has been added since I did that! Good catch. I have suggested one change, because oddly Pagination doesn't seem to have a `'light` prop so the two `--light` variant classes are not currently used by Carbon. If you agree and commit that change (you can do that easily here within github) I'll be happy to approve and merge! Thank you for your contribution.

2021-05-18 00:33 UTC, dcwarwick commented
@nertzy Also, as this PR changes the styles for a released component, there's an extra step needed to enable it to pass the CI check and be merged: we need to refresh the released styles snapshot. If you have a clone of ibm-cloud-cognitive where you can run builds etc, you'll need to run `yarn jest styles -u` in this branch, commit the updated snapshot file, and push it to update this PR.

PS alternatively I'll be very happy to do this step for you if you like, but you'll need to allow me -- if you look at the bottom right side of this PR and tick the checkbox
![image](https://user-images.githubusercontent.com/6385315/118572664-e15f2680-b778-11eb-9b11-8f87760c2019.png)
then that enables us to adjust PRs for you. It's normally a good idea to leave that checkbox ticked as it can speed things up.

2021-05-18 17:05 UTC, nertzy commented
Thanks for the feedback! I'm having trouble getting node-sass compiled with my latest version of NodeJS, so I'll defer to you to make the requested changes.

I don't see the checkbox you mentioned, so I'm going to try putting this PR back into draft mode to see if that allows me to make that change.

2021-05-18 17:23 UTC, nertzy commented
I set up nvm on my machine real quick and was able to get the snapshot generated. Let me know if there are any other edits I should make. Thanks!

2021-05-19 11:17 UTC, merged