Apikey review updates
carbon-design-system/ibm-cloud-cognitive pull request #985
Opened 2021-07-12 15:07 UTC by davidmenendez

Contributes to #954 

address the issues brought up in the review of ApiKeyModal with two major inclusions including adding an edit mode and refactoring certain functions to use `useEffect` instead. i also removed all the prop comments, which i will fix in another PR as well as finishing testing for editing.

2021-07-12 20:49 UTC, davidmenendez commented
cc @dcwarwick @lee-chase

2021-07-14 10:44 UTC, lee-chase requested changes

2021-07-14 10:44 UTC, lee-chase commented on packages/cloud-cognitive/src/components/APIKeyModal/APIKeyModal.js
> +      visibilityToggle,
Review requested this was renamed to `hasAPIKeyVisibilityToggle`

2021-07-14 10:44 UTC, lee-chase commented on packages/cloud-cognitive/src/components/APIKeyModal/APIKeyModal.js
> +const customStepsRequiredProps = isRequiredIf(
Using PropTypes.string.isRequired.if directly in propTypes will add an * to the field in storybook documentation. Also worth adding a comment/note to the comment in propTypes e.g. NOTE: This prop is only required if customSteps are supplied.

2021-07-14 10:44 UTC, lee-chase commented on packages/cloud-cognitive/src/components/APIKeyModal/APIKeyModal.js
> +  ({ customSteps }) => customSteps.length > 1
```suggestion
  ({ customSteps }) => customSteps && customSteps.length > 1
```

2021-07-15 17:01 UTC, davidmenendez commented
@lee-chase @dcwarwick changes made

2021-07-15 20:39 UTC, davidmenendez commented
@lee-chase @dcwarwick i was giving these changes some additional thought in regards to the use of `useEffect` and i have concluded that the original code was optimal as it was. i did some further research and using `useEffect` here to derive conditionals from props doesn't have any additional benefit and in reality causes additional unnecessary rerenders. any props that are going to effect the state of the modal are already going to cause a rerender, so we don't need to keep track of it in our own state. it's perfectly fine to just use standard variables here.

2021-07-19 10:53 UTC, lee-chase approved these changes

2021-07-19 14:41 UTC, merged